version: 2

project_name: akeylesstos3

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -w -s
    binary: akeylesstos3

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers_v2:
  - images:
      - "ghcr.io/jdavid77/akeyless-to-s3"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.url": "https://github.com/Jdavid77/akeyless-to-s3"
      "org.opencontainers.image.source": "https://github.com/Jdavid77/akeyless-to-s3"
      "org.opencontainers.image.description": "Exports secrets from Akeyless to AWS S3 as an encrypted zip archive."
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - /etc/ssl/certs/ca-certificates.crt
