version: 2

project_name: akeylesstos3

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -w -s
    binary: akeylesstos3

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/Jdavid77/akeyless-to-s3"
      - "--label=org.opencontainers.image.source=https://github.com/Jdavid77/akeyless-to-s3"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.description=Exports secrets from Akeyless to AWS S3 as an encrypted zip archive."
    extra_files:
      - /etc/ssl/certs/ca-certificates.crt
